# Generated by Django 4.2.4 on 2023-08-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pribadi', '0002_portfolio_kategori_alter_portfolio_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='kategori',
            field=models.CharField(blank=True, choices=[('web_dev', 'WEB Development'), ('creative_design', 'Creative Design'), ('graphic_design', 'Graphic Design')], max_length=250, null=True),
        ),
    ]
