# Generated by Django 4.2.4 on 2023-08-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pribadi', '0003_alter_portfolio_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='kategori_dua',
            field=models.CharField(blank=True, choices=[('web_dev', 'WEB Development'), ('creative_design', 'Creative Design'), ('graphic_design', 'Graphic Design')], max_length=250, null=True),
        ),
    ]
